### PR TITLE
Use shared notification center delegate

### PR DESCRIPTION
**Pull request by edusperoni**
Initial implementation.

Tests pending.

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Exciting stuff mate!!

**Comment by edusperoni** [comment]
It seems this travis failure isn't related to this PR.

I've tested it with the demo app on iOS and haven't run into any issues. @EddyVerbruggen if you could validate it, it would be amazing!

Once this and https://github.com/EddyVerbruggen/nativescript-plugin-firebase/pull/1272 are properly tested I'll release `nativescript-shared-notification-delegate@1.0.0` prior to the merge.

**Comment by markoImake** [comment]
I tried @edusperoni's version and it resolved my issues with the appdelegate being overwritten. Haven't experienced any other issues. Keen to get this merged.

**Comment by EddyVerbruggen** [comment]
Works like a charm, thanks! And sorry for the delay.

**Pull request merged**
